### =================
### Production
### =================

## Get the reported words
GET https://wordgames.goodsky.dev/api/connections/report


### Clear the report
DELETE https://wordgames.goodsky.dev/api/connections/report

### =================
### DEVELOPMENT
### (Localhost)
### =================

## Get the reported words
GET http://localhost:3000/api/connections/report


### Clear the report
DELETE http://localhost:3000/api/connections/report

### Send a report
POST http://localhost:3000/api/connections/report
Content-Type: application/json

{
    "gameId": "test",
    "words": ["example", "testword", "anotherword"],
    "comment": "These are test words for reporting."
}