### =================
### Production
### =================

## Get the reported words
GET https://spellingbee.goodsky.dev/api/dictionary/report


### Clear the report
DELETE https://spellingbee.goodsky.dev/api/dictionary/report


### =================
### DEVELOPMENT
### =================

### Get the report
GET http://localhost:3000/api/dictionary/report


### Clear the report
DELETE http://localhost:3000/api/dictionary/report


### Report a word
POST http://localhost:3000/api/dictionary/report
Content-Type: application/json

{
    "word": "SKYLER",
    "type": "remove"
}


### Get a New Game
GET http://localhost:3000/api/newgame


### Get the dictionary
POST http://localhost:3000/api/dictionary
Content-Type: application/json

{
    "letters": ["a", "b", "c", "d", "e", "f", "g"],
    "minLength": 4
}

